# Generated by Django 3.0.3 on 2020-03-01 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='shop.Category', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='good',
            name='desc',
            field=models.CharField(blank=django.db.models.deletion.CASCADE, max_length=100, null=True, verbose_name='商品描述'),
        ),
        migrations.CreateModel(
            name='GoodImgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='goodimg', verbose_name='商品展示图')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='shop.Good', verbose_name='商品')),
            ],
        ),
    ]
